### ISSUE TITLE
Major UI Bug

### ISSUE THREAD

**Issue by ZacharyKhan** [mownier/sambag#5]
I downloaded your demo project, built and ran. 

When presenting any of the pickers, I get a very distorted UI. I am running on **iPhone X,** **latest iOS 11.X.X** and **latest Xcode**.

![img_0456aa70a04a-1](https://user-images.githubusercontent.com/14354004/35950823-4dbb868e-0c2d-11e8-8d55-f8803c2422e4.jpeg)

**Comment by mownier** [comment]
I can not reproduce this. I built and ran the project and I did not encounter this problem. I am using Xcode 9.0.1, iOS 11.0, iPhone X simulator. Version 1.0.1, which has a fix on layout issues on changing orientation, resolves this issue supposedly.

- Can you discuss the steps to reproduce this? 
- What is the exact version of Xcode you are using?
- Are you running an iPhone X simulator or device?
- What is the exact iOS version?

**Comment by nerezza07** [comment]
I'm having the same issue if I run using big iphone such as iPhone 6plus, 7plus.

**Comment by ZacharyKhan** [comment]
@mownier  How are you laying out the views? Are you calculating & setting the frame or are you using AutoLayout constraints?

**Comment by nerezza07** [comment]
I found the issue from my side.
It is because when we set the frame of WheelViewController inside the SambagDatePickerViewController somehow it doesn't reflect on the WheelViewController. 

So inside the WheelViewController, we have to set the frame again. I think it happens on **iOS 11.2 onwards.** 
There should be more elegant way to do this but this one works for me right now. 

<img width="665" alt="screen shot 2018-02-13 at 11 12 36 am" src="https://user-images.githubusercontent.com/7554293/36131825-d30de27a-10ae-11e8-8085-df2bc9138d68.png">

**Comment by MiteshMungara** [comment]
I have updated code for ios 11. Now GUI problem is solved. Any one wants code replay me

**Comment by taier** [comment]
fix https://github.com/taier/sambag/commit/6cf685c31f3209bfd126c395f4525483fce7c951

**Comment by taier** [comment]
@mownier vote to close
